services:
  - type: static
    name: big-diet-system
    buildCommand: npm install
    staticPublishPath: ./
    plan: free
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
